import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/ui/theme/theme-provider";
import { TooltipProvider } from "@/components/ui/tooltip";
import ConvexClientProvider from "@/providers/ConvexClientProvider";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const PoppinsFont = Poppins({
	variable: "--font-poppins",
	subsets: ["latin"],
	weight: ["100", "200", "300", "400"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Michat :)",
	description: "Generated by Tyler",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${PoppinsFont.className} sans-serif`}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<ConvexClientProvider>
						<TooltipProvider>{children}</TooltipProvider>
					</ConvexClientProvider>
				</ThemeProvider>
				<Toaster richColors />
			</body>
		</html>
	);
}
